DROP TABLE IF EXISTS customer;
CREATE TABLE customer(
	id INT(11) AUTO_INCREMENT NOT NULL,
	name VARCHAR(64) NOT NULL,
	address VARCHAR(64) NOT NULL,
	zipcode VARCHAR(64) NOT NULL,
	fax VARCHAR(64) NOT NULL,
	PRIMARY KEY(id)
)ENGINE=InnoDB,DEFAULT CHARSET=utf8;